#!perl
sub on_user_command {
    my ($self, $cmd) = @_;
    if ($cmd eq "fullscreen:switch") {
        my $dummy = `wmctrl -r :ACTIVE: -b toggle,fullscreen,above` ;
	my $wid = `xdotool getactivewindow` ;
	chomp $wid ;
        my $dummy2 = `xdotool windowsize ${wid} 100% 50%` ;
    }
}
